movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:movie_id>", views.detail, name="details")
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import Movieresource
from . import views


movie_resource = Movieresource()


urlpatterns = [
    path("", views.home_page),
    path('admin/', admin.site.urls),
    path("movies/", include("movies.urls")),
    path("api/", include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie
# Create your models here.


class Movieresource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = "movies"

movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    rental_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Movie
# Create your views here.


def index(request):
    movies = Movie.objects.all()
    return render(request, "movie/index.html", {"movies": movies})


def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    return render(request, "movie/detail.html", {"movie": movie})

vidly/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, "home.html")

movies/templates/movie/detail.html
{% extends "base.html" %} {% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{movie.title}}</dd>
  <dt>Year</dt>
  <dd>{{movie.release_year}}</dd>
  <dt>Stock</dt>
  <dd>{{movie.number_in_stock}}</dd>
</dl>

{% endblock%}

movies/templates/movie/index.html
{% extends 'base.html'%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Title</title>
  </head>
  <body>
    {%block content %}
    <table class="table table-bodered table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Genre</th>
          <th>Stock</th>
          <th>Daily Rate</th>
        </tr>
      </thead>
      <tbody>
        {%for movie in movies %}
        <tr>
          <td>
            <a href="{%url  'movies:details' movie.id %}">{{movie.title}}</a>
          </td>
          <td>{{movie.genre}}</td>
          <td>{{movie.number_in_stock}}</td>
          <td>{{movie.rental_rate}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {%endblock%}
  </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    <title>Vidly</title>
  </head>
  <body>
    <!-- As a link -->
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/">Vidly</a>
    </nav>

    <main class="container">{%block content %} {%endblock%}</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} {%block content %}
<a href="{%url 'movies:index' %}">Movies</a>
{%endblock%}